# TASK 1-Identify and Characterize Data Sources

In [1]:
Dataset_A=[
    {"username": "ali01", "email": "ali@example.com", "age": 25, "signup_date": "2023-01-10"},
    {"username": "leyla_h", "email": "leyla@test.com", "age": 30, "signup_date": "2023-02-15"},
    {"username": "murad99", "email": "murad_at_gmail.com", "age": 22, "signup_date": "2023-03-01"},  
    {"username": "fidan_v", "email": "fidan@site.com", "age": "28", "signup_date": "2023-03-05"},   
    {"username": "", "email": "anonim@mail.com", "age": 40, "signup_date": "2023-03-10"},           
    {"username": "nurana19", "email": "nuranali19@mail.az", "age": 19, "signup_date": "2023-03-12"},
    {"username": "aygun_z", "email": "aygun@web.com", "age": 35, "signup_date": "2023-03-15"},
    {"username": "kamran_o", "email": "kamran@code.edu", "age": 27, "signup_date": "2023-03-20"}
]

def validate_registrations(entries):
    valid_entries = []
    invalid_entries = []

    for entry in entries:
        username = entry.get("username")
        email = entry.get("email")
        age = entry.get("age")

        is_valid = True

        # Username check
        if not username:
            is_valid = False

        # Email check
        if not isinstance(email, str) or "@" not in email:
            is_valid = False

        # Age check
        try:
            age_int = int(age)
            if age_int <= 0:
                is_valid = False
        except:
            is_valid = False

        if is_valid:
            valid_entries.append(entry)
        else:
            invalid_entries.append(entry)

    return valid_entries, invalid_entries


valid, invalid = validate_registrations(Dataset_A)

print("Valid entries count:", len(valid))
print("Invalid entries count:", len(invalid))

Valid entries count: 6
Invalid entries count: 2

This dataset represents user input data. Since users enter the information themselves, it is likely to contain errors such as invalid emails, missing usernames, or incorrect data types (for example, age written as text). 

In production, common quality issues would be missing values, wrong formats, duplicate accounts, or unrealistic ages. 

Before using this data in an ML pipeline, I would validate that:
- username is not empty
- email contains "@" and follows a basic format
- age is a positive integer
- signup_date has a valid date format

In [2]:
Dataset_B=[
  {"timestamp": "2026-03-02 10:00:01", "service": "Auth-Service", "level": "INFO", "message": "User 'admin' logged in successfully."},
  {"timestamp": "2026-03-02 10:00:05", "service": "Payment-Gateway", "level": "INFO", "message": "Processing transaction ID #99821."},
  {"timestamp": "2026-03-02 10:01:12", "service": "Inventory-Manager", "level": "WARNING", "message": "Low stock detected for Item ID #402."},
  {"timestamp": "2026-03-02 10:02:45", "service": "Auth-Service", "level": "ERROR", "message": "Failed login attempt from IP 192.168.1.50."},
  {"timestamp": "2026-03-02 10:03:20", "service": "Payment-Gateway", "level": "ERROR", "message": "Connection timeout with banking API."},
  {"timestamp": "2026-03-02 10:04:10", "service": "Inventory-Manager", "level": "INFO", "message": "Inventory sync completed."},
  {"timestamp": "2026-03-02 10:05:00", "service": "Auth-Service", "level": "INFO", "message": "Password reset token generated for user 'jdoe'."},
  {"timestamp": "2026-03-02 10:06:15", "service": "Payment-Gateway", "level": "WARNING", "message": "Late response from payment processor."},
  {"timestamp": "2026-03-02 10:07:30", "service": "Inventory-Manager", "level": "ERROR", "message": "Database connection lost while updating stock."},
  {"timestamp": "2026-03-02 10:08:05", "service": "Auth-Service", "level": "INFO", "message": "User 'guest_99' session expired."}
]

This dataset represents system-generated data. Logs are automatically created by applications or services.

Possible quality issues include missing timestamps, inconsistent log levels, duplicated logs, or corrupted entries during system failures.

Before using it in ML, I would:
- ensure timestamps are valid and properly formatted
- check that log levels are limited to INFO, WARNING, or ERROR
- remove duplicates
- handle missing or empty messages

In [3]:
Dataset_C=[
  {"sku": "PRD-1001","product_name": "Wireless Mouse M350","quantity_in_stock": 120,"warehouse_location": "Baku-North-A1","last_updated": "2026-03-01 09:15:20"},
  {"sku": "PRD-2025","product_name": "Mechanical Keyboard K85","quantity_in_stock": 45,"warehouse_location": "Sumqayit-West-B3","last_updated": "2026-02-28 14:30:00"},
  {"sku": "PRD-3050","product_name": "Monitor 27-inch 4K","quantity_in_stock": 12,"warehouse_location": "Baku-North-A2","last_updated": "2026-03-02 11:05:45"},
  {"sku": "PRD-4012","product_name": "USB-C Hub 7-in-1","quantity_in_stock": 210,"warehouse_location": "Ganja-East-C1","last_updated": "2026-03-01 17:40:10"},
  {"sku": "PRD-5099","product_name": "Laptop Stand Pro","quantity_in_stock": 0,"warehouse_location": "Baku-North-A1","last_updated": "2026-02-25 08:00:00"},
  {"sku": "PRD-6123","product_name": "Noise Cancelling Headphones","quantity_in_stock": 88,"warehouse_location": "Sumqayit-West-B2","last_updated": "2026-03-02 10:22:30"}
]

this dataset represents internal database data. It likely comes from a company’s inventory management system.

Possible quality issues include incorrect stock quantities, outdated last_updated fields, or inconsistent warehouse locations.

Before using it in ML, I would:
- ensure quantity_in_stock is a non-negative number
- validate SKU uniqueness
- check that last_updated is a valid datetime
- confirm warehouse_location matches known locations

# Task 2: Work with Multiple Data Formats

In [4]:
#step 1
import pandas as pd
import numpy as np
import csv
import io

np.random.seed(19)  

rides = pd.DataFrame({
    "ride_id": range(1, 501),
    "driver_id": np.random.randint(1000, 1051, 500),
    "distance_km": np.random.uniform(1.0, 30.0, 500),
    "fare_usd": np.random.uniform(5.0, 75.0, 500),
    "ride_type": np.random.choice(["standard", "premium", "pool"], 500),
    "city": np.random.choice(["Berlin", "Seoul", "Nairobi", "Toronto", "Lima"], 500),
    "timestamp": pd.date_range(start="2025-01-01", periods=500, freq="min")
})
rides.head()

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1029,21.851465,57.801548,standard,Berlin,2025-01-01 00:00:00
1,2,1046,19.819872,18.490549,standard,Nairobi,2025-01-01 00:01:00
2,3,1034,6.193740,47.830693,standard,Nairobi,2025-01-01 00:02:00
3,4,1040,6.428698,47.176822,pool,Berlin,2025-01-01 00:03:00
4,5,1019,22.305689,66.616433,standard,Lima,2025-01-01 00:04:00

In [5]:
#step 2

#saving data in csv
rides.to_csv("rides.csv", index=False)
#saving data in json
rides.to_json("rides.json", orient="records", lines=True)
#saving data in parquet
rides.to_parquet("rides.parquet", index=False)

C:\Users\pc\AppData\Local\Temp\ipykernel_37024\2918730721.py:6: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  rides.to_json("rides.json", orient="records", lines=True)

In [6]:
#step 3

import os

csv_size = os.path.getsize("rides.csv")
json_size = os.path.getsize("rides.json")
parquet_size = os.path.getsize("rides.parquet")

csv_kb = csv_size / 1024
json_kb = json_size / 1024
parquet_kb = parquet_size / 1024

print(f"CSV size: {csv_kb:.2f} KB")
print(f"JSON size: {json_kb:.2f} KB")
print(f"Parquet size: {parquet_kb:.2f} KB")

ratio = csv_size / parquet_size
print(f"\nParquet is {ratio:.2f} times smaller than CSV")

CSV size: 39.51 KB
JSON size: 72.50 KB
Parquet size: 20.34 KB

Parquet is 1.94 times smaller than CSV

In [7]:
#step 4

rides_csv = pd.read_csv("rides.csv")
rides_json = pd.read_json("rides.json",orient="records",lines=True)
rides_parquet = pd.read_parquet("rides.parquet")

#comparing shapes
print("Original shape:", rides.shape)
print("CSV shape:", rides_csv.shape)
print("JSON shape:", rides_json.shape)
print("Parquet shape:", rides_parquet.shape)

#comparing data types
print("\nOriginal dtypes:")
print(rides.dtypes)
print("\nCSV dtypes:")
print(rides_csv.dtypes)
print("\nJSON dtypes:")
print(rides_json.dtypes)
print("\nParquet dtypes:")
print(rides_parquet.dtypes)

#comparing samples
print("\nOriginal sample:")
print(rides.head(3))

print("\nCSV sample:")
print(rides_csv.head(3))

print("\nJSON sample:")
print(rides_json.head(3))

print("\nParquet sample:")
print(rides_parquet.head(3))

Original shape: (500, 7)
CSV shape: (500, 7)
JSON shape: (500, 7)
Parquet shape: (500, 7)

Original dtypes:
ride_id                 int64
driver_id               int32
distance_km           float64
fare_usd              float64
ride_type                 str
city                      str
timestamp      datetime64[us]
dtype: object

CSV dtypes:
ride_id          int64
driver_id        int64
distance_km    float64
fare_usd       float64
ride_type          str
city               str
timestamp          str
dtype: object

JSON dtypes:
ride_id                 int64
driver_id               int64
distance_km           float64
fare_usd              float64
ride_type                 str
city                      str
timestamp      datetime64[ms]
dtype: object

Parquet dtypes:
ride_id                 int64
driver_id               int32
distance_km           float64
fare_usd              float64
ride_type                 str
city                      str
timestamp      datetime64[us]
dtype: object

Original sample:
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1029    21.851465  57.801548  standard   Berlin
1        2       1046    19.819872  18.490549  standard  Nairobi
2        3       1034     6.193740  47.830693  standard  Nairobi

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00

CSV sample:
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1029    21.851465  57.801548  standard   Berlin
1        2       1046    19.819872  18.490549  standard  Nairobi
2        3       1034     6.193740  47.830693  standard  Nairobi

             timestamp
0  2025-01-01 00:00:00
1  2025-01-01 00:01:00
2  2025-01-01 00:02:00

JSON sample:
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1029    21.851465  57.801548  standard   Berlin
1        2       1046    19.819872  18.490549  standard  Nairobi
2        3       1034     6.193740  47.830693  standard  Nairobi

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00

Parquet sample:
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1029    21.851465  57.801548  standard   Berlin
1        2       1046    19.819872  18.490549  standard  Nairobi
2        3       1034     6.193740  47.830693  standard  Nairobi

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00

All three formats kept the same shape (500 rows, 7 columns).
CSV changed the timestamp column to string because it stores data as plain text.

JSON preserved the datetime type, but the precision changed from microseconds to milliseconds.

Parquet preserved all original data types exactly, including datetime and integer precision.

Overall, Parquet kept the data most accurately.

#step 5
From the comparison, Parquet preserved the data types most faithfully. It kept the datetime column and integer precision exactly the same as in the original DataFrame. CSV changed the timestamp to string, and JSON slightly reduced the datetime precision.

Parquet was also the smallest file. This is because it uses a binary columnar format and compression, while CSV and JSON store everything as plain text.

I would choose CSV if I need a simple and human-readable format that works everywhere. I would choose JSON when working with APIs or semi-structured data. However, for analytics or machine learning tasks, I would choose Parquet because it preserves types better and is more efficient for large datasets.

# Task 3: Row-Major vs Column-Major Access Patterns

In [8]:
#step 1
import time

np.random.seed(19)
data = np.random.rand(200_000, 20)
columns = [f"feature_{i}" for i in range(20)]
df = pd.DataFrame(data, columns=columns)

print(df.shape)

#step 2
%time df["feature_0"].mean()

(200000, 20)
CPU times: total: 0 ns
Wall time: 1.17 ms

np.float64(0.49959742799195256)

In [9]:
%%timeit
total = 0
for i in range(10_000):
    total += df.iloc[i]["feature_0"]

403 ms ± 19.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Column access using df["feature_0"].mean() was very fast (around 1.8 ms).

Row iteration over the first 10,000 rows using df.iloc[i] took around 90 ms.

This shows that column-based vectorized operations in pandas are much faster than manually iterating over rows. The row loop is significantly slower because it runs in Python and creates additional overhead for each access.

In [10]:
#step 3
arr = df.to_numpy()
%time arr[:, 0].mean()

CPU times: total: 0 ns
Wall time: 495 μs

np.float64(0.49959742799195256)

In [11]:
%%timeit

total = 0
for i in range(10_000):
    total += arr[i, 0]

2.54 ms ± 28.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

NumPy column access (arr[:, 0].mean()) was very fast, around 0.5 ms.

Row iteration over the first 10,000 rows took around 2.5 ms.

This shows that in NumPy, vectorized column operations are faster than manual row loops. However, NumPy row access is still more efficient than pandas row iteration because it works directly with contiguous memory and has less overhead.

#step 4

1) Column access in pandas is faster because pandas is mainly optimized for column-based operations. When we use df["feature_0"].mean(), the calculation runs in a vectorized way and is optimized in the background. But when we iterate row by row using df.iloc[i], it works at the Python level and creates extra overhead, so it becomes slower.

2) When using NumPy, the gap becomes smaller because NumPy works directly with arrays and does not create extra objects like pandas does. It accesses memory more directly, so even row loops are relatively faster compared to pandas.

3) This shows that both pandas and NumPy are designed mainly for column-oriented data access. The data is stored column by column in memory, so column operations are more efficient. Row-by-row processing does not match this structure, so it is slower.

# Task 4: Text vs Binary Format Deep Dive

In [12]:
#step 1
np.random.seed(42)

data = np.random.rand(100_000, 5)
columns = [f"num_{i}" for i in range(5)]
df_= pd.DataFrame(data, columns=columns)

df_["category"] = np.random.choice(
    ["alpha", "beta", "gamma"],
    size=100_000
)
print(df_.shape)
df_.head()

(100000, 6)

      num_0     num_1     num_2     num_3     num_4 category
0  0.374540  0.950714  0.731994  0.598658  0.156019    alpha
1  0.155995  0.058084  0.866176  0.601115  0.708073    gamma
2  0.020584  0.969910  0.832443  0.212339  0.181825     beta
3  0.183405  0.304242  0.524756  0.431945  0.291229    alpha
4  0.611853  0.139494  0.292145  0.366362  0.456070    gamma

In [13]:
#step 2
df_.to_csv("large_data.csv", index=False)
df_.to_parquet("large_data.parquet", index=False)

csv_size = os.path.getsize("large_data.csv") / 1024
parquet_size = os.path.getsize("large_data.parquet") / 1024

print(f"CSV size: {csv_size:.2f} KB")
print(f"Parquet size: {parquet_size:.2f} KB")

print(f"Parquet is {csv_size / parquet_size:.2f} times smaller than CSV")

CSV size: 10060.03 KB
Parquet size: 4926.58 KB
Parquet is 2.04 times smaller than CSV

In [14]:
#step 3
df_csv = pd.read_csv("large_data.csv")
df_parquet = pd.read_parquet("large_data.parquet")

print("CSV dtypes:")
print(df_csv.dtypes)

print("\nParquet dtypes:")
print(df_parquet.dtypes)

CSV dtypes:
num_0       float64
num_1       float64
num_2       float64
num_3       float64
num_4       float64
category        str
dtype: object

Parquet dtypes:
num_0       float64
num_1       float64
num_2       float64
num_3       float64
num_4       float64
category        str
dtype: object

After reading the files back, the numeric columns were preserved correctly in both CSV and Parquet as float64.

The category column was read as object type in CSV because CSV stores everything as plain text. Parquet preserved the schema more reliably, and in some cases it can keep categorical information more efficiently.

In general, Parquet preserves data types more faithfully because it stores metadata about the schema, while CSV only stores raw text.

In [15]:
#step 4
%time pd.read_csv("large_data.csv")
%time pd.read_parquet("large_data.parquet")

CPU times: total: 156 ms
Wall time: 153 ms
CPU times: total: 15.6 ms
Wall time: 14.3 ms

          num_0     num_1     num_2     num_3     num_4 category
0      0.374540  0.950714  0.731994  0.598658  0.156019    alpha
1      0.155995  0.058084  0.866176  0.601115  0.708073    gamma
2      0.020584  0.969910  0.832443  0.212339  0.181825     beta
3      0.183405  0.304242  0.524756  0.431945  0.291229    alpha
4      0.611853  0.139494  0.292145  0.366362  0.456070    gamma
...         ...       ...       ...       ...       ...      ...
99995  0.405318  0.602591  0.458201  0.302946  0.460695    alpha
99996  0.179499  0.967898  0.876744  0.368456  0.098493    gamma
99997  0.638458  0.404135  0.756854  0.817779  0.549797    alpha
99998  0.213876  0.822076  0.705511  0.765023  0.964082    alpha
99999  0.665520  0.989442  0.487741  0.664987  0.626668    alpha

[100000 rows x 6 columns]

In [16]:
#step 5 
%time category_only = pd.read_parquet("large_data.parquet", columns=["category"])

CPU times: total: 15.6 ms
Wall time: 7.58 ms

Full Parquet read: 13.8 ms
Category-only read: 7.76 ms

Reading only the "category" column from the Parquet file was faster than reading the full dataset.

This is possible because Parquet stores data in a columnar format. Each column is stored separately, so the system can load only the columns that are needed.

In contrast, CSV stores data row by row as plain text. Because of this structure, the whole file must be read and parsed even if we only need one column.

# Task 5: Representation Choices and Trade-Offs

In [17]:
#step 1
data = [
    {"title": "Clean Code", "author": "Robert C. Martin", "format": "Paperback", "publisher_name": "Prentice Hall", "publisher_country": "USA", "price": 32},
    {"title": "Clean Code", "author": "Robert C. Martin", "format": "E-book", "publisher_name": "Prentice Hall", "publisher_country": "USA", "price": 22},

    {"title": "The Pragmatic Programmer", "author": "Andrew Hunt", "format": "Paperback", "publisher_name": "Addison-Wesley", "publisher_country": "USA", "price": 35},
    {"title": "The Pragmatic Programmer", "author": "Andrew Hunt", "format": "E-book", "publisher_name": "Addison-Wesley", "publisher_country": "USA", "price": 24},

    {"title": "Introduction to Algorithms", "author": "Thomas H. Cormen", "format": "Paperback", "publisher_name": "MIT Press", "publisher_country": "USA", "price": 80},

    {"title": "Design Patterns", "author": "Erich Gamma", "format": "Paperback", "publisher_name": "Addison-Wesley", "publisher_country": "USA", "price": 40},

    {"title": "Python Crash Course", "author": "Eric Matthes", "format": "Paperback", "publisher_name": "No Starch Press", "publisher_country": "USA", "price": 30},

    {"title": "Deep Learning", "author": "Ian Goodfellow", "format": "E-book", "publisher_name": "MIT Press", "publisher_country": "USA", "price": 50},

    {"title": "Artificial Intelligence: A Modern Approach", "author": "Stuart Russell", "format": "Paperback", "publisher_name": "Pearson", "publisher_country": "UK", "price": 70},

    {"title": "You Don't Know JS", "author": "Kyle Simpson", "format": "E-book", "publisher_name": "O'Reilly Media", "publisher_country": "USA", "price": 20},

    {"title": "Fluent Python", "author": "Luciano Ramalho", "format": "Paperback", "publisher_name": "O'Reilly Media", "publisher_country": "USA", "price": 45},

    {"title": "Data Science from Scratch", "author": "Joel Grus", "format": "Paperback", "publisher_name": "O'Reilly Media", "publisher_country": "USA", "price": 38}
]


df_books = pd.DataFrame(data)

df_books

,title,author,format,publisher_name,publisher_country,price
0,Clean Code,Robert C. Martin,Paperback,Prentice Hall,USA,32
1,Clean Code,Robert C. Martin,E-book,Prentice Hall,USA,22
2,The Pragmatic Programmer,Andrew Hunt,Paperback,Addison-Wesley,USA,35
3,The Pragmatic Programmer,Andrew Hunt,E-book,Addison-Wesley,USA,24
4,Introduction to Algorithms,Thomas H. Cormen,Paperback,MIT Press,USA,80
5,Design Patterns,Erich Gamma,Paperback,Addison-Wesley,USA,40
6,Python Crash Course,Eric Matthes,Paperback,No Starch Press,USA,30
7,Deep Learning,Ian Goodfellow,E-book,MIT Press,USA,50
8,Artificial Intelligence: A Modern Approach,Stuart Russell,Paperback,Pearson,UK,70
9,You Don't Know JS,Kyle Simpson,E-book,O'Reilly Media,USA,20
10,Fluent Python,Luciano Ramalho,Paperback,O'Reilly Media,USA,45
11,Data Science from Scratch,Joel Grus,Paperback,O'Reilly Media,USA,38

In [18]:
# Step 2 
publishers = df_books[["publisher_name", "publisher_country"]].drop_duplicates().reset_index(drop=True)
publishers["publisher_id"] = publishers.index + 1
publishers = publishers[["publisher_id","publisher_name","publisher_country"]]

books = df_books.merge(publishers, on=["publisher_name","publisher_country"])
books = books[["title","author","format","publisher_id","price"]]

joined = books.merge(publishers, on="publisher_id")

joined = joined[["title","author","format","publisher_name","publisher_country","price"]]

flat_sorted = df_books.sort_values(by=["title","format"]).reset_index(drop=True)
joined_sorted = joined.sort_values(by=["title","format"]).reset_index(drop=True)

print("Joined equals flat version:", joined_sorted.equals(flat_sorted))

Joined equals flat version: True

In [19]:
documents = []

for title, g in df_books.groupby("title"):
    documents.append({
        "title": title,
        "author": g["author"].iloc[0],
        "publisher": {
            "publisher_name": g["publisher_name"].iloc[0],
            "publisher_country": g["publisher_country"].iloc[0]
        },
        "editions": g[["format", "price"]].to_dict("records")
    })

documents[0]

{'title': 'Artificial Intelligence: A Modern Approach',
 'author': 'Stuart Russell',
 'publisher': {'publisher_name': 'Pearson', 'publisher_country': 'UK'},
 'editions': [{'format': 'Paperback', 'price': 70}]}

In [20]:
author_name = "Robert C. Martin"
publisher_to_update = "O'Reilly Media"
new_country = "Ireland"

In [21]:
#flat
# Q1
flat_by_author = df_books[df_books["author"] == author_name][["title", "format", "price"]]
print("FLAT - books by author:\n", flat_by_author, "\n")

# Q2
flat_avg_price = df_books["price"].mean()
print("FLAT - average price:", flat_avg_price, "\n")

# Q3
flat_mask = df_books["publisher_name"] == publisher_to_update
flat_rows_to_change = flat_mask.sum()

df_books_flat_updated = df_books.copy()
df_books_flat_updated.loc[flat_mask, "publisher_country"] = new_country

print("FLAT - rows to change:", flat_rows_to_change)

FLAT - books by author:
         title     format  price
0  Clean Code  Paperback     32
1  Clean Code     E-book     22

FLAT - average price: 40.5

FLAT - rows to change: 3

In [22]:
#normalized 

# Q1
norm_by_author = books[books["author"] == author_name][["title", "format", "price", "publisher_id"]]
print("\nNORMALIZED - books by author:\n", norm_by_author, "\n")

# Q2
norm_avg_price = books["price"].mean()
print("NORMALIZED - average price:", norm_avg_price, "\n")

# Q3
pub_mask = publishers["publisher_name"] == publisher_to_update
publishers_rows_to_change = pub_mask.sum()   

publishers_updated = publishers.copy()
publishers_updated.loc[pub_mask, "publisher_country"] = new_country

print("NORMALIZED - rows to change in publishers table:", publishers_rows_to_change)

NORMALIZED - books by author:
         title     format  price  publisher_id
0  Clean Code  Paperback     32             1
1  Clean Code     E-book     22             1

NORMALIZED - average price: 40.5

NORMALIZED - rows to change in publishers table: 1

In [23]:
#Document

# Q1
doc_by_author = [d for d in documents if d["author"] == author_name]
print("\nDOCUMENT - books by author:")
for d in doc_by_author:
    print("-", d["title"], "editions:", len(d["editions"]))

# Q2
all_prices = [ed["price"] for d in documents for ed in d["editions"]]
doc_avg_price = sum(all_prices) / len(all_prices)
print("\nDOCUMENT - average price:", doc_avg_price)

# Q3
docs_to_change = sum(1 for d in documents if d["publisher"]["publisher_name"] == publisher_to_update)

documents_updated = []
for d in documents:
    d2 = d.copy()
    d2["publisher"] = d["publisher"].copy()
    if d2["publisher"]["publisher_name"] == publisher_to_update:
        d2["publisher"]["publisher_country"] = new_country
    documents_updated.append(d2)

print("\nDOCUMENT - documents to change:", docs_to_change)

DOCUMENT - books by author:
- Clean Code editions: 2

DOCUMENT - average price: 40.5

DOCUMENT - documents to change: 3

For finding all books by a specific author, the flat and normalized versions were easier because we can directly filter by the author column. In the document version we need to loop through the documents.

For calculating the average price across all editions, the flat and normalized versions were also simpler since price is just a column and we can use `.mean()`. In the document version we first need to collect prices from the editions list.

Updating a publisher’s country is easiest in the normalized version. In this structure the publisher information is stored only once in the publishers table, so usually only one record needs to be updated. In the flat and document versions the publisher data is repeated, so multiple rows or documents may need to change.

If publisher information changes frequently, the normalized structure is better because it avoids duplicated data. If each book is usually accessed as a single record, the document-oriented version is more convenient because all related information (publisher and editions) is stored together in one document.